import { Conversation, ReplyMessageType } from '../../types';

export const conversation: Conversation = {
  id: 'conv_ai_assistant_001',
  participants: [
    {
      id: 'user_001',
      name: 'Sarah Mitchell',
      avatar: 'https://i.pravatar.cc/150?img=5',
      status: 'online',
    },
    {
      id: 'ai_assistant_001',
      name: 'AI Assistant',
      avatar: 'https://i.pravatar.cc/300?img=56',
      status: 'online',
    },
  ],
  messages: [
    {
      id: 'msg_001',
      senderId: 'user_001',
      text: 'Hi! Can you help me plan a project timeline?',
      timestamp: '2026-02-17T10:00:00Z',
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg_002',
      senderId: 'ai_assistant_001',
      text: "Of course! I'd be happy to help you plan a project timeline. To create the best plan, could you tell me:",
      timestamp: '2026-02-17T10:00:30Z',
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg_003',
      senderId: 'ai_assistant_001',
      text: '1. What is the project about?\n2. What is your target completion date?\n3. How many team members are involved?',
      timestamp: '2026-02-17T10:00:45Z',
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg_004',
      senderId: 'user_001',
      text: "It's a mobile app redesign. We need to finish by end of March, and there are 4 of us.",
      timestamp: '2026-02-17T10:02:15Z',
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg_006',
      senderId: 'ai_assistant_001',
      text: "Great! Here's a suggested timeline for your mobile app redesign:",
      timestamp: '2026-02-17T10:03:00Z',
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg_007',
      senderId: 'ai_assistant_001',
      text: 'Week 1-2 (Feb 17-28): Planning & Design\n- Gather requirements\n- Create wireframes\n- Design mockups\n\nWeek 3-5 (Mar 1-21): Development\n- UI implementation\n- Integration\n- Testing\n\nWeek 6 (Mar 22-31): Polish & Deployment\n- Bug fixes\n- Performance optimization\n- Final testing & rollout',
      timestamp: '2026-02-17T10:03:30Z',
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg_008',
      senderId: 'user_001',
      text: 'That looks good! How should we allocate tasks among the team?',
      timestamp: '2026-02-17T10:05:00Z',
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg_009',
      senderId: 'ai_assistant_001',
      text: 'For a 4-person team, I recommend:',
      timestamp: '2026-02-17T10:05:30Z',
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg_010',
      senderId: 'ai_assistant_001',
      text: '• Lead Designer: Oversee design mockups & ensure consistency\n• Frontend Developer: Build UI components\n• Backend Developer: Handle API & integration\n• QA Engineer: Testing & bug tracking',
      timestamp: '2026-02-17T10:05:45Z',
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg_011',
      senderId: 'user_001',
      text: 'Perfect! Can you create a checklist for the design phase?',
      timestamp: '2026-02-17T10:07:00Z',
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg_013',
      senderId: 'ai_assistant_001',
      text: '✓ Finalize app requirements & user stories\n✓ Create user flow diagrams\n✓ Design wireframes for key screens\n✓ Create visual design system (colors, typography, components)\n✓ Design high-fidelity mockups\n✓ Gather stakeholder feedback\n✓ Iterate and refine designs\n✓ Hand off to development team',
      timestamp: '2026-02-17T10:07:45Z',
      status: 'read',
      type: 'text',
    },
    {
      id: 'msg_014',
      senderId: 'user_001',
      text: 'This is really helpful! One more thing - what are some common pitfalls we should avoid?',
      timestamp: '2026-02-17T10:09:00Z',
      status: 'read',
      type: 'text',
    },
  ],
  metadata: {
    createdAt: '2026-02-17T10:00:00Z',
    lastMessageAt: '2026-02-17T10:11:30Z',
    unreadCount: {
      user_001: 0,
      ai_assistant_001: 0,
    },
  },
};

export const assistantReplies: Record<ReplyMessageType, string[]> = {
  image: [
    'https://images.pexels.com/photos/35651783/pexels-photo-35651783.jpeg',
    'https://images.pexels.com/photos/33856992/pexels-photo-33856992.jpeg',
    'https://images.pexels.com/photos/33573602/pexels-photo-33573602.jpeg',
    'https://images.pexels.com/photos/35009194/pexels-photo-35009194.jpeg',
    'https://images.pexels.com/photos/35267956/pexels-photo-35267956.jpeg',
    'https://images.pexels.com/photos/36129740/pexels-photo-36129740.jpeg',
    'https://images.pexels.com/photos/34783013/pexels-photo-34783013.jpeg',
    'https://images.pexels.com/photos/35239054/pexels-photo-35239054.jpeg',
    'https://images.pexels.com/photos/36105985/pexels-photo-36105985.jpeg',
    'https://images.pexels.com/photos/35878569/pexels-photo-35878569.jpeg',
  ],
  text: [
    "Sure! I'd be happy to help you with that.",
    'Great question! Let me look into that for you.',
    "I understand what you're looking for. Here's what I found:",
    "Thanks for reaching out! Here's how you can approach this:",
    "Absolutely! Here's a step-by-step breakdown:",
    "That's an interesting topic. Let me explain:",
    "I've reviewed your request and here's my recommendation:",
    "Here's a summary of what you need to know:",
    'No problem! I can help you with that right away.',
    'Let me clarify that for you with a quick explanation:',
  ],
};
